### ISSUE TITLE
Video controls are unclear when the video background is white

### ISSUE THREAD

**Issue by PlayerMiller109** [PKM-er/media-extended#391]
<image width="500" src="https://github.com/PKM-er/media-extended/assets/145541890/4e2f5870-0faa-4e6a-91ae-aedfa254f314"><br>

Obsidian Current and Installer versions v1.6.5, Media Extended Plugin version v3.2.4, have tested in Sandbox Vault.

Possible solution: change CSS.

Workaround for now:

```css
[data-controls] > .inset-0.z-0::before {
  content: '';
  position: absolute;
  height: 70px;
  right: 0; bottom: 0; left: 0;
  background: linear-gradient(to bottom, transparent 0%, #22222290 100%);
}
```

<image width="500" src="https://github.com/PKM-er/media-extended/assets/145541890/6e0361ac-346e-4e97-8ed5-3fe51b1f6f82">
